let currentVideoPath=null;let hasResumeSession=false;let running=false;let currentSettings={};let healthTimer=null;
const $=id=>document.getElementById(id);
const selectVideoBtn=$('selectVideoBtn'),startBtn=$('startBtn'),cancelBtn=$('cancelBtn'),progressBar=$('progressBar'),progressPercent=$('progressPercent'),progressStatus=$('progressStatus'),progressText=$('progressText'),resumeBox=$('resumeBox'),discardSessionBtn=$('discardSessionBtn'),settingsMessage=$('settingsMessage'),selectedFile=$('selectedFile'),toast=$('toast');
function basename(path){const p=String(path||'').replaceAll('\\','/').split('/');return p[p.length-1]||''}
function showToast(message,isError=false){toast.textContent=message;toast.style.borderColor=isError?'#a64b5d':'#0eb7c2';toast.classList.remove('hidden');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.add('hidden'),3300)}
function setRunning(value){running=!!value;selectVideoBtn.disabled=running;startBtn.disabled=running||!currentVideoPath;cancelBtn.classList.toggle('hidden',!running);document.querySelectorAll('.nav-item').forEach(x=>x.disabled=running&&x.dataset.page!=='translate')}
function resetSteps(){document.querySelectorAll('.flow-step').forEach(s=>s.classList.remove('active','done'))}
function markStep(name,state){const e=document.querySelector(`[data-step="${name}"]`);if(!e)return;if(state==='active')e.classList.add('active');if(state==='done'){e.classList.remove('active');e.classList.add('done')}}
function renderStepState(percent,status){resetSteps();if(percent>=15)markStep('extract','done');else if(percent>0)markStep('extract','active');if(percent>=55)markStep('transcribe','done');else if(percent>=15)markStep('transcribe','active');if(percent>=85)markStep('translate','done');else if(percent>=55)markStep('translate','active');if(percent>=100)markStep('render','done');else if(percent>=85)markStep('render','active');if(status==='Cancelled'||status==='Failed')document.querySelectorAll('.flow-step.active').forEach(e=>e.classList.remove('active'))}
function updateProgress(percent,text,status){const n=Math.max(0,Math.min(100,Number(percent)||0));progressBar.style.width=`${n}%`;progressPercent.textContent=`${Math.round(n)}%`;progressStatus.textContent=status||'Working';progressText.textContent=text||'';renderStepState(n,status);if(status==='Completed'){setRunning(false);cancelBtn.disabled=false;hasResumeSession=false;resumeBox.classList.add('hidden');showToast('Translation completed successfully');refreshProjects();}else if(status==='Failed'){setRunning(false);cancelBtn.disabled=false;showToast(`Operation failed: ${text}`,true)}else if(status==='Cancelled'){setRunning(false);cancelBtn.disabled=false;hasResumeSession=true;resumeBox.classList.remove('hidden');showToast('Cancelled. Resume state has been saved.')}}window.updateProgress=updateProgress;
function paintHealth(s){currentSettings=s||currentSettings;const ready=!!s.ai_service_ready;$('aiHealth').textContent=ready?'Connected':'Waking up...';$('ffmpegHealth').textContent=s.ffmpeg_ready?'Ready':'Not found';$('ffprobeHealth').textContent=s.ffprobe_ready?'Ready':'Not found';renderAboutHealth(s)}
async function refreshSettings(){try{const s=await pywebview.api.get_settings();currentSettings=s;paintHealth(s);$('outputDirInput').value=s.output_dir||'';$('gatewayHost').textContent=s.gateway_host||'—';$('autoOpenOutput').checked=!!s.auto_open_output;$('translationChunkSize').value=s.translation_chunk_size||15;$('transcriptionChunkMinutes').value=s.transcription_chunk_minutes||10;$('subtitleFont').value=s.subtitle_font_name||'Arial';$('subtitleFontSize').value=s.subtitle_font_size||24}catch(e){console.error(e)}}
async function refreshAiHealth(){if(running)return;try{const r=await pywebview.api.test_ai_service();if(r?.success){$('aiHealth').textContent='Connected';currentSettings.ai_service_ready=true}else{$('aiHealth').textContent='Waking up...';currentSettings.ai_service_ready=false}renderAboutHealth(currentSettings)}catch(e){$('aiHealth').textContent='Waking up...'}}
function renderAboutHealth(s){const el=$('aboutHealth');if(!el)return;el.innerHTML=`<div class="info-box"><b>AI Service</b><span>${s.ai_service_ready?'Connected':'Waking up...'}</span></div><div class="info-box"><b>FFmpeg</b><span>${s.ffmpeg_ready?'Ready':'Not found'}</span></div><div class="info-box"><b>ffprobe</b><span>${s.ffprobe_ready?'Ready':'Not found'}</span></div>`}
async function chooseVideo(){const result=await pywebview.api.select_video();if(!result)return;if(String(result).startsWith('ERROR:')){showToast(String(result),true);return}currentVideoPath=result;$('videoPath').value=result;selectedFile.textContent=basename(result);selectedFile.classList.remove('hidden');startBtn.disabled=false;hasResumeSession=await pywebview.api.has_resumable_session(result);resumeBox.classList.toggle('hidden',!hasResumeSession)}
selectVideoBtn.addEventListener('click',chooseVideo);
const dropZone=$('dropZone');['dragenter','dragover'].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.remove('dragover')}));dropZone.addEventListener('drop',async e=>{const f=e.dataTransfer?.files?.[0];const path=f?.path||f?.webkitRelativePath;if(path){const result=await pywebview.api.set_video_path(path);if(result?.success){currentVideoPath=result.path;selectedFile.textContent=basename(result.path);selectedFile.classList.remove('hidden');startBtn.disabled=false;hasResumeSession=await pywebview.api.has_resumable_session(result.path);resumeBox.classList.toggle('hidden',!hasResumeSession);return}}showToast('Could not read the dropped file path. Use Choose Video instead.',true)});
discardSessionBtn.addEventListener('click',async()=>{if(!currentVideoPath)return;await pywebview.api.discard_session(currentVideoPath);hasResumeSession=false;resumeBox.classList.add('hidden');showToast('Resume session removed')});
startBtn.addEventListener('click',async()=>{if(!currentVideoPath||running)return;updateProgress(0,hasResumeSession?'Resuming previous session...':'Preparing task...','Starting');setRunning(true);const result=await pywebview.api.start_full_pipeline(currentVideoPath,hasResumeSession);if(!result.success){setRunning(false);showToast(result.message||'Could not start processing',true)}});
cancelBtn.addEventListener('click',async()=>{if(!running)return;cancelBtn.disabled=true;await pywebview.api.cancel_operation();progressText.textContent='Stopping safely and saving resume state...'});
function openPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===name));const page=$(`page-${name}`);if(page)page.classList.add('active');if(name==='projects')refreshProjects();if(name==='logs')refreshLogs();if(name==='about'||name.includes('settings')||name==='general')refreshSettings()}
document.querySelectorAll('.nav-item').forEach(n=>n.addEventListener('click',()=>openPage(n.dataset.page)));$('quickSettingsBtn').addEventListener('click',()=>openPage('general'));
async function saveAllSettings(){const payload={output_dir:$('outputDirInput').value.trim(),auto_open_output:$('autoOpenOutput').checked,translation_chunk_size:Number($('translationChunkSize').value),transcription_chunk_minutes:Number($('transcriptionChunkMinutes').value),subtitle_font_name:$('subtitleFont').value,subtitle_font_size:Number($('subtitleFontSize').value)};const r=await pywebview.api.save_preferences(payload);if(r.success){showToast('Settings saved');settingsMessage.textContent='Settings saved.';await refreshSettings()}else{showToast(r.message||'Could not save settings',true)}}document.querySelectorAll('[data-save-settings]').forEach(b=>b.addEventListener('click',saveAllSettings));
$('chooseOutputBtn').addEventListener('click',async()=>{const r=await pywebview.api.select_output_folder();if(r&&!String(r).startsWith('ERROR:'))$('outputDirInput').value=r});$('openOutputBtn').addEventListener('click',()=>pywebview.api.open_output_folder());$('testServiceBtn').addEventListener('click',async()=>{showToast('Testing AI service...');const r=await pywebview.api.test_ai_service();showToast(r.message||'',!r.success);await refreshSettings()});
async function refreshProjects(){const list=$('projectsList');if(!list)return;list.innerHTML='<div class="empty-state">Loading projects...</div>';try{const projects=await pywebview.api.get_projects();if(!projects.length){list.innerHTML='<div class="empty-state">No translated videos yet.</div>';return}list.innerHTML=projects.map((p,i)=>`<article class="project-card"><h3>${escapeHtml(p.name)}</h3><div class="project-meta"><span>${escapeHtml(p.modified)}</span><span>${escapeHtml(p.size)}</span></div><div class="project-actions"><button class="outline-primary" data-open-project="${i}">Open Video</button><button class="soft-btn" data-open-folder="${i}">Open Folder</button></div></article>`).join('');list.querySelectorAll('[data-open-project]').forEach(b=>b.addEventListener('click',()=>pywebview.api.open_path(projects[Number(b.dataset.openProject)].video_path)));list.querySelectorAll('[data-open-folder]').forEach(b=>b.addEventListener('click',()=>pywebview.api.open_path(projects[Number(b.dataset.openFolder)].folder)))}catch(e){list.innerHTML='<div class="empty-state">Could not load projects.</div>'}}$('refreshProjectsBtn').addEventListener('click',refreshProjects);
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function refreshLogs(){const box=$('logsBox');box.textContent='Loading logs...';try{box.textContent=await pywebview.api.get_recent_logs(300)||'Log is empty.';box.scrollTop=box.scrollHeight}catch(e){box.textContent='Could not load logs.'}}$('refreshLogsBtn').addEventListener('click',refreshLogs);$('clearLogsBtn').addEventListener('click',async()=>{await pywebview.api.clear_logs();refreshLogs();showToast('Logs cleared')});
$('minimizeWindowBtn').addEventListener('click',()=>pywebview.api.window_minimize());$('maximizeWindowBtn').addEventListener('click',()=>pywebview.api.window_toggle_maximize());$('closeWindowBtn').addEventListener('click',()=>pywebview.api.window_close());
window.addEventListener('pywebviewready',async()=>{$('aiHealth').textContent='Connecting...';await refreshSettings();refreshProjects();clearInterval(healthTimer);healthTimer=setInterval(refreshAiHealth,10000);setTimeout(refreshAiHealth,2500)});
